from django.conf.urls.defaults import *

urlpatterns = patterns('commerce.views',
    (r'^dispatch-ad/$', 'dispatch_ad', {'tmpl': 'commerce/dispatch_ad.txt'}, 'dispath-ad'),
    (r'^verify-ad/(?P<ad_id>\d+)/$', 'verify_ad', {'tmpl': 'commerce/verify_ad.txt'}, 'verify-ad'),
    (r'^display-ad/(?P<ad_id>\d+)/$', 'display_ad', {'tmpl': 'commerce/display_ad.html'} , 'display-ad'),
    (r'^store-list/$', 'get_store_list'),
    (r'^activity-deal/$','activity_deals', {'tmpl': 'admin/activity_deal.html'}, 'activity_deal'),
    (r'^set-activity-position/$', 'set_activity_position'), 
    (r'^dispatch-store-ad/$', 'dispatch_store_ad',{'tmpl': 'commerce/dispatch_store_ad.txt'}, 'dispatch-store-ad'),
    (r'^mini/$', 'get_mini',{'tmpl': 'commerce/dispatch_mini.txt'}, 'mini'),
    (r'^show-mini/$', 'show_mini',{'tmpl':'commerce/show_mini.html'}, 'show-mini'),
    (r'^verify-mini/$', 'verify_mini', {'tmpl': 'commerce/verify_mini.txt'}, 'verify-mini'),
    (r'^review/$', 'review', {'tmpl': 'commerce/review.html'}, 'review'),
    (r'^share/$', 'share_to_community'),
    (r'^show-my-collection/$', 'show_my_collection', {'tmpl': 'commerce/show_my_collection.html'}, 'show-my-collection'),
    (r'^recommand-apps/$', 'recommand_apps'),
    (r'^show-app/(?P<app_id>\d+)/$', 'show_app', {'tmpl': 'commerce/show_app.html'}, 'show_app'),
    (r'^record-app-access/$', 'record_app_access'),
    (r'^record-app-click/$', 'record_app_click'),
    (r'^ajax-show-app-click/$', 'show_app_audit_from_ajax'),
    (r'^show-app-click-audit/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$', 'show_app_click_audit'),
    (r'^record-mini-click/', 'record_mini_click'),
    (r'^show-mini-click-audit/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/$', 'show_mini_click_audit'),
)
